# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:

  ##############################################################
  test-vedo-vtk9:

    machine:
      image: ubuntu-2004:current

    resource_class: medium

    environment:
      MPLBACKEND: "agg"
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - checkout

      - run:
          name: installing vedo
          command: |
            sudo apt-get update
            sudo apt install libgl1-mesa-dev xvfb -y
            pip3 install vedo
            pip3 install matplotlib
            pip3 install scipy
            pip3 install --no-deps .

      - run:
          name: Run tests
          command: |
            cd
            cd project/tests/common
            source run_all.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports


  ##############################################################
  build-dolfinx:
    docker:
      - image: quay.io/fenicsproject/dolfinx:dev-env-real
    environment:
      MPLBACKEND: "agg"
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - checkout

      - run:
          name: install vedo et al
          command: |
            pip3 install vtk
            pip3 install .

      # FEniCS:
      - run:
          name: Get dolfinx cmake compile and install
          command: |
            pip3 install git+https://github.com/FEniCS/fiat.git --upgrade
            pip3 install git+https://github.com/FEniCS/ufl.git  --upgrade
            pip3 install git+https://github.com/FEniCS/ffcx.git --upgrade
            rm -rf /usr/local/include/dolfin /usr/local/include/dolfin.h
            git clone https://github.com/FEniCS/dolfinx.git
            cd dolfinx
            mkdir -p build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer ../cpp/
            ninja -j3 install
            cd ../python
            pip3 -v install . --user

      - run:
          name: Run tests
          command: |
            cd
            cd project/tests/dolfinx
            source run_all.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports

######################################################
workflows:
  version: 2
  build-stuff:
    jobs:
      #- test-vedo-vtk7
      - test-vedo-vtk9
      #- build-dolfin-stable
      #- build-dolfinx




